export {
  onAuthChange,
  signInWithEmail,
  signOutFirebase,
  signUpWithEmail,
} from './firebase-auth';
export {
  buildVersionMap,
  type CompactionMigrationResult,
  createInitialSyncMetadata,
  type DailyUsageRecord,
  deleteArchivedItems,
  deleteMcHistoryItems,
  deletePresets,
  deleteQuestionHistoryItems,
  deleteSavedSets,
  type DeltaSyncResult,
  getChangedItems,
  getDeltaItems,
  getDeltaSyncData,
  getRemoteHistoryCounts,
  isRemotePresetsArrayDifferent,
  loadChangedItems,
  loadUserData,
  migrateUserDataForCompaction,
  replacePresets,
  saveAnalyticsSummary,
  saveDailyUsage,
  type SaveOptions,
  saveUserData,
  type SyncableData,
  type SyncMetadata,
  upsertGoals,
  upsertMcHistoryItems,
  upsertPresets,
  upsertQuestionHistoryItems,
  upsertSavedSets,
} from './firebase-crud';
export { app, auth, db, type FirebaseUser } from './firebase-init';
